
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: anjoman_db
      POSTGRES_USER: anjoman_user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

    env_file:
      - .env

  worker:
    build: .
    command: celery -A anjoman_web worker -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

    env_file:
      - .env

volumes:   
  postgres_data: